### PR TITLE
Add Django > 3.0 support

### PR DESCRIPTION
**Pull request by ikcam**

### CODE REVIEW

**Comment by jonashaag** [comment]
Let’s instead drop six entirely and inline the text_type definition for the single place where it’s used.

**Comment by jonashaag** [comment]
Thanks but that’s what I meant. text_type is different in Python 2 and Python 3.

**Comment by ikcam** [comment]
You mean like:
```python
import sys

PY2 = sys.version_info[0] == 2

def text_type(value):
    return unicode(value) if PY2 else str(value)
```

**Comment by jonashaag** [comment]
Yep

**Comment by jonashaag** [comment]
Thank you!

**Pull request merged**
