### PR TITLE
Fix #110: Tests failing on Django 1.10

### PR DESCRIPTION
**Pull request by jpic**
I'd really like the opinion of @blueyed on 7d33913, cause that's really weird,
looks like a bug in pytest-django.

### CODE REVIEW

**Comment by blueyed** [comment]
@jpic 
Strange, I could not find anything in the release notes in this regard (https://docs.djangoproject.com/en/dev/releases/1.10/), but only searched for "live" and "allow".

pytest-django's tests pass on Django 1.10 (from the branch): https://github.com/pytest-dev/pytest-django/pull/344.

Example build failure: https://travis-ci.org/jonashaag/django-addanother/jobs/139062953

**Comment by blueyed** [comment]
According to https://github.com/jonashaag/django-addanother/pull/19#issuecomment-227546805 only Django master is affected.

**Comment by blueyed** [comment]
https://docs.djangoproject.com/en/dev/releases/1.11/#miscellaneous mentions:

> ALLOWED_HOSTS validation is no longer disabled when running tests. If your application includes tests with custom host names, you must include those host names in ALLOWED_HOSTS. See [Tests and multiple host names](https://docs.djangoproject.com/en/dev/topics/testing/advanced/#topics-testing-advanced-multiple-hosts).

**Comment by jonashaag** [comment]
@blueyed Wow, nicely debugged ;) Thanks! I suggest merging your Django 1.10/master PR, and for Django master, @jpic's `ALLOWED_HOSTS` change but with `localhost` instead of `*`. Does that sound reasonable?

**Comment by jonashaag** [comment]
Oh btw Django 1.11 will support Python 3.4 as well

**Comment by blueyed** [comment]
> Oh btw Django 1.11 will support Python 3.4 as well

Yes, but I've thought that it's enough to test expected failures with only one version of both Python 2 and 3.

**Comment by jpic** [comment]
Indeed, we have in tox:

django110: https://github.com/django/django/archive/master.tar.gz

​Updating pr

**Comment by jpic** [comment]
Closing in favor of #19

**Pull request closed without merging**
