### PR TITLE
New implementation leveraging django admin's one

### PR DESCRIPTION
**Pull request by jpic**

### CODE REVIEW

**Comment by jpic** [comment]
SLOC differences in the actual app directory:

Before:

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           3             37             25            102
JavaScript                       1              8              1             45
-------------------------------------------------------------------------------
SUM:                             4             45             26            147
-------------------------------------------------------------------------------
```

After:

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             24              1             82
HTML                             1              1              0              9
JavaScript                       1              0              0              2
-------------------------------------------------------------------------------
SUM:                             4             25              1             93
-------------------------------------------------------------------------------
```

Perhaps Thomas could implement the comments you've posted in https://github.com/yourlabs/django-addanother/commit/c3fb88338c71dc6638528588144f42ffe3ad5320 ?

**Comment by jonashaag** [comment]
What do you think about builtin select2 widget wrappers? I found that to be very practical to quickly have a nice looking UI

**Comment by jpic** [comment]
Sure, perhaps in addanother.contrib.select2 ?

**Comment by jonashaag** [comment]
Sounds good! I'll try to find some time to fix my nitpicks the next days and then merge this.

**Comment by jonashaag** [comment]
Actually, since my concerns are all minor code quality things, let's just get this done and fix these things later.

Do you know if I can give permissions to additional people for PyPI administration?

**Pull request merged**
